# Generated by Django 5.1.1 on 2024-12-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="brief_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
