# Generated by Django 5.1.1 on 2024-12-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0004_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="contact_email",
        ),
    ]
