# Generated by Django 5.1.1 on 2024-12-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0005_remove_profile_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
    ]
