# Generated by Django 5.1.1 on 2024-12-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0006_remove_project_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="GitHub",
            new_name="Link",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="LinkedIn",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="Whatsapp",
        ),
    ]
