# Generated by Django 5.1.1 on 2024-12-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0007_rename_github_contact_link_remove_contact_linkedin_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="Link",
        ),
    ]
