# Generated by Django 5.1.1 on 2024-12-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0008_remove_contact_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="GitHub",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="LinkedIn",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="Whatsapp",
            field=models.URLField(blank=True, null=True),
        ),
    ]
