# Generated by Django 5.1.1 on 2024-12-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0009_contact_github_contact_linkedin_contact_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
