# Generated by Django 5.1.1 on 2024-12-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0010_alter_skill_proficiency"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="PHONE",
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
    ]
