# Generated by Django 5.1.1 on 2024-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0011_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Institue", models.CharField(max_length=100)),
                ("Degree", models.CharField(max_length=100)),
                ("Graduation_year", models.DateField(blank=True, null=True)),
                (
                    "Picture",
                    models.ImageField(blank=True, null=True, upload_to="Images/"),
                ),
            ],
        ),
    ]
