# Generated by Django 5.1.1 on 2024-12-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0014_alter_skill_proficiency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
