# Generated by Django 5.1.1 on 2024-12-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0015_alter_education_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="Start_year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
