# Generated by Django 5.1.1 on 2025-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0016_education_start_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="imgs/"),
        ),
    ]
