# Generated by Django 5.1.1 on 2025-01-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0017_certificate_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="imgs/"),
        ),
    ]
