# Generated by Django 5.1.1 on 2025-01-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0018_alter_education_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="imgs/"),
        ),
    ]
