# Generated by Django 5.1.1 on 2025-01-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0019_project_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="cv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CV", models.FileField(blank=True, null=True, upload_to="files/")),
            ],
        ),
    ]
