# Generated by Django 5.1.1 on 2025-01-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0020_cv"),
    ]

    operations = [
        migrations.DeleteModel(
            name="cv",
        ),
        migrations.AddField(
            model_name="contact",
            name="CV",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
    ]
