# Generated by Django 5.1.1 on 2025-01-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0021_delete_cv_contact_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="Instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="X",
            field=models.URLField(blank=True, null=True),
        ),
    ]
